import React,{useEffect,useState} from 'react';import{createRoot}from'react-dom/client';import'./styles.css';import{trace,replay}from'./data';
type Screen='traces'|'runner'|'replay'|'report';
const nav:{id:Screen;label:string}[]=[{id:'traces',label:'Traces'},{id:'runner',label:'Scenario runner'},{id:'replay',label:'Replay detail'},{id:'report',label:'Divergence report'}];
function Metric({label,value}:{label:string,value:string}){return <div className="metric"><span>{label}</span><strong>{value}</strong></div>}
function Timeline({fault=false}:{fault?:boolean}){return <ol className="timeline" aria-label="Event timeline">{trace.events.map((e,i)=><li key={e[1]}><time>{e[0]}</time><i className={fault&&i===1?'fault':''}/><div><b>{e[1]}</b><small>seq {i+1} · {e[2]}</small>{fault&&i===1&&<em>injected duplicate</em>}</div></li>)}</ol>}
function Traces({go}:{go:(s:Screen)=>void}){return <><header><div><p>CAPTURED WORKFLOWS</p><h1>Event traces</h1></div><span className="live">● seeded fixture</span></header><section className="panel"><div className="toolbar"><label>Filter traces<input placeholder="Correlation ID or event type"/></label><button onClick={()=>go('runner')}>Run scenario</button></div><button className="traceRow" onClick={()=>go('replay')}><div><b>Reservation payout</b><code>{trace.correlationId}</code></div><Metric label="Events" value="5"/><Metric label="Duration" value={trace.duration}/><Metric label="Throughput" value={trace.throughput}/><span className="ok">complete →</span></button></section><section className="split"><div className="panel"><h2>Selected trace</h2><Timeline/></div><div className="panel dense"><h2>Final state</h2><pre>{JSON.stringify({reservationStatus:'CONFIRMED',depositAuthorized:true,refundStatus:'NONE',payoutStatus:'SENT'},null,2)}</pre></div></section></>}
function Runner({go}:{go:(s:Screen)=>void}){const[running,setRunning]=useState(false);useEffect(()=>{if(running){const t=setTimeout(()=>{setRunning(false);go('replay')},900);return()=>clearTimeout(t)}},[running]);return <><header><div><p>CONTROLLED EXPERIMENT</p><h1>Scenario runner</h1></div></header><section className="split"><div className="panel form"><label>Source correlation ID<input value={trace.correlationId} readOnly/></label><label>Fault scenario<select defaultValue="duplicate"><option value="duplicate">Duplicate payment authorization</option><option>Drop refund request</option><option>Dependency timeout + retries</option></select></label><div className="grid"><label>Seed<input type="number" defaultValue="101"/></label><label>Checkpoint<input type="number" defaultValue="0"/></label></div><button disabled={running} onClick={()=>setRunning(true)}>{running?'Compiling schedule…':'Start deterministic replay'}</button>{running&&<p role="status" className="progress">Replay is running. This page can stay open.</p>}</div><div className="panel"><h2>Compiled intent</h2><dl><dt>Selector</dt><dd>DepositAuthorized</dd><dt>Mutation</dt><dd>Duplicate ×1</dd><dt>Execution</dt><dd>Fixed epoch · isolated</dd><dt>Limits</dt><dd>100 source events · 3 duplicates</dd></dl></div></section></>}
function Replay({go}:{go:(s:Screen)=>void}){return <><header><div><p>REPLAY / {replay.id}</p><h1>Replay detail</h1></div><span className="ok">● {replay.status}</span></header><div className="metrics"><Metric label="Duration" value={replay.duration}/><Metric label="Throughput" value={replay.throughput}/><Metric label="Injected faults" value="1"/><Metric label="Violations" value="1 hard"/></div><section className="split"><div className="panel"><h2>Replay timeline</h2><Timeline fault/></div><div className="panel"><h2>Execution evidence</h2><p className="faultbox">{replay.fault}</p><code>{trace.correlationId}</code><button onClick={()=>go('report')}>Open divergence report →</button></div></section></>}
function Report(){return <><header><div><p>CAUSAL COMPARISON</p><h1>Divergence report</h1></div><button>Export JSON</button></header><section className="alert"><b>First divergence at event 3</b><span>Duplicate authorization changed financial-effect cardinality before payout.</span></section><section className="split"><div className="panel"><h2>Invariant violations</h2>{replay.violations.map(v=><article className="violation"><span>{v.severity}</span><b>{v.rule}</b><p>Position {v.position} · {v.actual}</p></article>)}</div><div className="panel"><h2>Final-state diff</h2><table><thead><tr><th>Field</th><th>Baseline</th><th>Replay</th></tr></thead><tbody>{replay.diff.map(d=><tr><th>{d[0]}</th><td>{d[1]}</td><td className="changed">{d[2]}</td></tr>)}</tbody></table></div></section></>}
function App(){const[screen,setScreen]=useState<Screen>((location.hash.slice(1)as Screen)||'traces');const go=(s:Screen)=>{location.hash=s;setScreen(s)};return <div className="shell"><aside><a className="brand" href="#traces">RF<span>ReplayForge</span></a><nav aria-label="Primary">{nav.map(n=><button aria-current={screen===n.id?'page':undefined} onClick={()=>go(n.id)}>{n.label}</button>)}</nav><small>Local development<br/>API v1</small></aside><main>{screen==='traces'?<Traces go={go}/>:screen==='runner'?<Runner go={go}/>:screen==='replay'?<Replay go={go}/>:<Report/>}</main></div>};createRoot(document.getElementById('root')!).render(<App/>);
